[Packaging] support uninstalling package
elastic/apm-agent-php pull request #222
Opened 2020-10-13 15:29 UTC by v1v

### What

- Provide the uninstall before script to delete any of the entries that were added when the agent was installed.

For such it will remove the entries:

```
; THIS IS AN AUTO-GENERATED FILE by the Elastic PHP agent post-install.sh script
extension=.*
elastic_apm.bootstrap_php_part_file=.*
; END OF AUTO-GENERATED by the Elastic PHP agent post-install.sh script
```

- Add uninstallation testing that validates the just installed package gets uninstalled successfully.
- Add uninstallation testing which does the installation too, in the CI.

### Why

Uninstall should not leave any leftovers

### Tests

### Issues

Closes #212

WIP

2020-10-13 15:31 UTC, v1v commented on packaging/Makefile
> +uninstall: apk-uninstall deb-uninstall rpm-uninstall  ## Uninstall all the distributions
tar-uninstall is not supported

2020-10-13 15:42 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-php%2Fapm-agent-php-mbp%2FPR-222/detail/PR-222/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-php%2Fapm-agent-php-mbp%2FPR-222/detail/PR-222/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-php%2Fapm-agent-php-mbp%2FPR-222/detail/PR-222/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-php%2Fapm-agent-php-mbp%2FPR-222/detail/PR-222/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-agent-php_222.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #222 opened]`

* Start Time: 2020-10-13T15:29:49.521+0000

* Duration: 12 min 14 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 444  |
| Skipped      | 0 |
| Total        | 444   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-php%2Fapm-agent-php-mbp%2FPR-222/detail/PR-222/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `package install`
    * Description: 
    
    * Duration: 2 min 56 sec
    
    * Start Time: 2020-10-13T15:39:31.977+0000
    
    * [log](https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-php/pipelines/apm-agent-php-mbp/pipelines/PR-222/runs/1/steps/620/log)
    
  
  * **Name**: `package install`
    * Description: 
    
    * Duration: 2 min 8 sec
    
    * Start Time: 2020-10-13T15:39:41.599+0000
    
    * [log](https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-php/pipelines/apm-agent-php-mbp/pipelines/PR-222/runs/1/steps/631/log)
    
  
  * **Name**: `package install`
    * Description: 
    
    * Duration: 2 min 3 sec
    
    * Start Time: 2020-10-13T15:39:48.049+0000
    
    * [log](https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-php/pipelines/apm-agent-php-mbp/pipelines/PR-222/runs/1/steps/642/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-13T15:41:50.905Z] Recording test results
[2020-10-13T15:41:51.177Z] Makefile:159: recipe for target 'deb-uninstall' failed
[2020-10-13T15:41:51.177Z] make: *** [deb-uninstall] Error 2
[2020-10-13T15:41:51.177Z] make: Leaving directory '/var/lib/jenkins/workspace/ent-php_apm-agent-php-mbp_PR-222/src/go.elastic.co/apm/apm-agent-php/packaging'
[2020-10-13T15:41:52.136Z] Failed in branch Matrix - PHP_VERSION = '7.3'
[2020-10-13T15:41:52.258Z] Post stage
[2020-10-13T15:41:52.288Z] Recording test results
[2020-10-13T15:41:53.387Z] Failed in branch Matrix - PHP_VERSION = '7.4'
[2020-10-13T15:41:53.826Z] Stage "Testing" skipped due to earlier failure(s)
[2020-10-13T15:41:54.713Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.724Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.737Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.749Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.760Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.771Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.781Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'redis'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.790Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'redis'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.801Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'redis'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.811Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'memcached'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.822Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'memcached'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.831Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'memcached'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.840Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'mysql'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.850Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'mysql'" skipped due to earlier failure(s)
[2020-10-13T15:41:54.862Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'mysql'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.278Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.294Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.304Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.313Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.324Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.335Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.345Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'redis'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.354Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'redis'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.365Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'redis'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.376Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'memcached'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.386Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'memcached'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.397Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'memcached'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.407Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'mysql'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.418Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'mysql'" skipped due to earlier failure(s)
[2020-10-13T15:41:55.430Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'mysql'" skipped due to earlier failure(s)
[2020-10-13T15:41:56.597Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:56.614Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:56.624Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'nginx'" skipped due to earlier failure(s)
[2020-10-13T15:41:56.635Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:56.644Z] Stage "Matrix - PHP_VERSION = '7.3', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:56.655Z] Stage "Matrix - PHP_VERSION = '7.4', FRAMEWORK = 'apache'" skipped due to earlier failure(s)
[2020-10-13T15:41:56.665Z] Stage "Matrix - PHP_VERSION = '7.2', FRAMEWORK = 'redis'" skipped due to earlier failure(s)
[2020-10- [...]

2020-10-14 15:20 UTC, cachedout requested changes

2020-10-14 15:20 UTC, cachedout commented on packaging/test/alpine/entrypoint.sh
> +if [ "${TYPE}" = "apk-uninstall" ] ; then
```suggestion
if [ "${TYPE}" == "apk-uninstall" ] ; then
```

2020-10-14 15:34 UTC, v1v commented on packaging/test/alpine/entrypoint.sh
> +if [ "${TYPE}" = "apk-uninstall" ] ; then
Alpines uses `sh` rather than `bash` and the shellcheck was saying something about the POSIX 

![image](https://user-images.githubusercontent.com/2871786/96011570-f9fe0b80-0e3a-11eb-983e-dfd59ae18da4.png)

https://www.shellcheck.net/wiki/SC2039

2020-10-14 15:39 UTC, cachedout commented on packaging/test/alpine/entrypoint.sh
> +if [ "${TYPE}" = "apk-uninstall" ] ; then
Ah! OK. I didn't really this was POSIX sh. This is correct then.

2020-10-14 15:39 UTC, cachedout approved these changes

2020-10-15 11:55 UTC, SergeyKleyman approved these changes

2020-10-15 12:05 UTC, merged