action: store syslogs if any failures in test-packages
elastic/apm-agent-php pull request #886
Opened 2023-03-09 12:20 UTC by v1v

Does what it says in the tin

2023-03-09 12:51 UTC, reakaleek approved these changes

2023-03-09 18:39 UTC, SergeyKleyman approved these changes

2023-03-09 18:40 UTC, SergeyKleyman reviewed
Let me test it on a dummy PR with a failure

2023-03-10 10:52 UTC, v1v commented on .github/workflows/test.yml
> +          find build/syslog -name "syslog" -exec bash -c 'mv {} "build/syslog/${ELASTIC_APM_PHP_TESTS_MATRIX_ROW}-$(basename {})"' \;
Good finding @SergeyKleyman 
```
Run find build/syslog -name "syslog" -exec bash -c 'mv {} "build/syslog/${ELASTIC_APM_PHP_TESTS_MATRIX_ROW}-$(basename {})"' \;
mv: cannot move 'build/syslog' to a subdirectory of itself, 'build/syslog/8.1,rpm,lifecycle,cli,with_ext_svc-syslog'
mv: cannot move 'build/syslog/messages' to 'build/syslog/8.1,rpm,lifecycle,cli,with_ext_svc-messages': Permission denied
```

2023-03-10 10:56 UTC, v1v commented on .github/workflows/test.yml
> +          find build/syslog -name "messages" -exec bash -c 'mv {} "build/syslog/${ELASTIC_APM_PHP_TESTS_MATRIX_ROW}-$(basename {})"'  \;
```suggestion
          cd build/syslog || true
          find . -name "syslog" -exec bash -c 'mv {} "${ELASTIC_APM_PHP_TESTS_MATRIX_ROW}-$(basename {})"' \;
          find . -name "messages" -exec bash -c 'mv {} "${ELASTIC_APM_PHP_TESTS_MATRIX_ROW}-$(basename {})"'  \;
```

2023-03-10 15:56 UTC, SergeyKleyman requested changes
I've tested it at https://github.com/elastic/apm-agent-php/pull/892 I found an issue. `syslogs.zip` contains only 107 files while there 115 failed test matrix rows. Syslog files are missing for all the rows with `agent_syslog_level=`.

2023-03-20 09:32 UTC, v1v commented
> I've tested it at https://github.com/elastic/apm-agent-php/pull/892 I found an issue. syslogs.zip contains only 107 files while there 115 failed test matrix rows. Syslog files are missing for all the rows with agent_syslog_level=.

Good catch, I ended up replacing any special chars for `-`, see https://github.com/elastic/apm-agent-php/pull/886/commits/a3e4f1d65544b9e40444e6e23db35d8b504c8c03

2023-03-20 10:53 UTC, v1v commented
I've just updated https://github.com/elastic/apm-agent-php/pull/892 with the recent changes in this PR, let's see how it goes

2023-03-20 11:29 UTC, v1v commented
> I've tested it at https://github.com/elastic/apm-agent-php/pull/892 I found an issue. syslogs.zip contains only 107 files while there 115 failed test matrix rows. Syslog files are missing for all the rows with agent_syslog_level=.

That's expected, as far as I see the env variable `gent_syslog_level=.` is created on the fly hence `ELASTIC_APM_PHP_TESTS_MATRIX_ROW` is not unique.

For instance, https://github.com/elastic/apm-agent-php/actions/runs/4467374976/jobs/7846912654#step:5:1127
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/2871786/226326815-ebeb4acb-1f34-4c77-a098-b7bd7537fbf4.png">

is not using `agent_syslog_level=TRACE`, need to figure out how it's created

2023-03-20 11:31 UTC, SergeyKleyman commented
Also I see that syslog files for all `rpm` rows are empty files (0 bytes). It seems `rsyslog` is not actually working on CentOS containers.

2023-03-23 15:15 UTC, SergeyKleyman approved these changes

2023-03-23 15:20 UTC, SergeyKleyman commented on .github/workflows/test.yml
> +      ELASTIC_APM_PHP_TESTS_MATRIX_ROW: "${{ matrix.item[0] }},${{ matrix.item[1] }},${{ matrix.item[2] }},${{ matrix.item[3] }},${{ matrix.item[4] }},${{ matrix.item[5] || 'noop=noop'}}"
I am not 100% why `noop` part is necessary. Could you clarify that please?

2023-03-23 15:33 UTC, v1v commented on .github/workflows/test.yml
> +      ELASTIC_APM_PHP_TESTS_MATRIX_ROW: "${{ matrix.item[0] }},${{ matrix.item[1] }},${{ matrix.item[2] }},${{ matrix.item[3] }},${{ matrix.item[4] }},${{ matrix.item[5] || 'noop=noop'}}"
The 5th element is not mandatory but optional, hence I had to use a default value, I chose `noop` but it could be anything. The reason, `ELASTIC_APM_PHP_TESTS_MATRIX_ROW` is the unique identifier, so I needed a dummy 5th element in the row, otherwise the syslogs when using `agent_syslog_level=` won't be stored but overriden.

2023-03-24 11:42 UTC, amannocci approved these changes

2023-03-24 12:07 UTC, merged