Migrate specs update to updatecli
elastic/apm-agent-php pull request #889
Opened 2023-03-09 14:13 UTC by reakaleek

2023-03-09 14:16 UTC, v1v commented on .ci/update-gherkin-specs.yml
> +
what do you think adding the fielld `pipelineid: 'update-gherkin-specs'` so the branch name is easy to recognise what's for?

2023-03-09 14:17 UTC, reakaleek commented on .ci/update-gherkin-specs.yml
> +
sure, will do also in the other PRs

2023-03-09 15:52 UTC, reakaleek commented on .ci/update-gherkin-specs.yml
> +
https://github.com/elastic/apm-agent-php/pull/889/commits/bd1cbcc032aec198c508e3b74403f7b3adda7198

2023-03-09 15:55 UTC, v1v approved these changes

2023-03-23 09:32 UTC, v1v requested changes

2023-03-23 09:32 UTC, v1v commented on .ci/updatecli.d/update-gherkin-specs.yml
> +      title: Update Gherkin specs
```suggestion
    title: '[Automation] Update Gherkin specs'
    spec:
```

2023-03-23 09:32 UTC, v1v commented on .ci/updatecli.d/update-json-specs.yml
> +      title: Update JSON specs
```suggestion
    title: '[Automation] Update JSON specs'
    spec:
```

2023-03-30 13:58 UTC, merged